Repository ComPWA/actions, pull requests merged in 2025-01, with the labels that each got.

#122 DX: update Epic label to include emoji💥
  .github/workflows/pr-linting.yml
Labels: 🖱️ DX

#123 FIX: set `CODECOV_TOKEN`
  .github/workflows/pytest.yml
Labels: 🐛 Bug

#125 FIX: run `pytest` with specified Python version
  .github/workflows/docnb.yml
  .github/workflows/linkcheck.yml
  .github/workflows/pre-commit.yml
  .github/workflows/pytest.yml
Labels: ⚙️ Enhancement, 🐛 Bug

#126 ENH: run documentation tests with `tox-uv`
  .github/workflows/docnb.yml
  .github/workflows/linkcheck.yml
Labels: ⚙️ Enhancement

#127 BEHAVIOR: run tests on Python 3.13
  create-pytest-matrix/main.py
Labels: ❗ Behavior

#128 ENH: don't update lock files if 'no-lock-upgrade'
  .github/workflows/lock.yml
Labels: ⚙️ Enhancement
